### ISSUE TITLE
Doesn't seem to build

### ISSUE THREAD

**Issue by jrmuizel** [rbran/sleigh3rust#2]
I get the following error when running `cargo build` at the root of the repo.

```
error[E0412]: cannot find type `SpacesStruct` in this scope
  --> toy_builder_le_align2/src/lib.rs:27:33
   |
27 |         &mut GlobalSetDefault::<SpacesStruct>::default(),
   |                                 ^^^^^^^^^^^^ not found in this scope
```

**Comment by rbran** [comment]
Fixed, the code was outdated. Thanks for pointing that out.

This is a highly experimental/unstable project at the moment, if you have any problems, please let me know.

BTW if you need a VM in rust, maybe [icicle-emu](https://github.com/icicle-emu/icicle-emu) could be a more stable alternative.

**Comment by jrmuizel** [comment]
I ended up trying out icicle-emu and prototyped an [icicle-disasm crate](https://github.com/jrmuizel/icicle-emu/tree/master/icicle-disasm) that let me get access to the pcode semantics for instructions. I'd prefer something where the sleigh code is used to generate a disassembler at compile time like sleigh-rs but this was good enough for my needs for now.
